org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
# 使用 build-tools 36.1.0 的 aapt2 解决 AGP 自带 aapt2 8.7.3 在 Windows 上无法编译资源的 bug
android.aapt2FromMavenOverride=D:/software/AndroidSDK/build-tools/36.1.0/aapt2.exe
